apiVersion: v1
kind: Secret
metadata:
  name: mcart-shared-secrets
  namespace: mcart
type: Opaque
stringData:
  AWS_ACCESS_KEY: "<replace-me>"
  AWS_SECRET_KEY: "<replace-me>"
  DB_PASSWORD: "<replace-me>"
  ES_BASE64_API_KEY: "<replace-with-elastic-api-key-or-empty>"